---
# XYZ Python/Django project
- hosts: XYZ
  user: chef
  sudo: yes
  tasks:
    - name: Create group for granting permissions
      group: name=devs state=present    
    #- name: Adding user john.doe to group
    #  shell: useradd -G devs john.doe
    - name: Setting up custom privileges to web directory
      action: file path=/var/www/html/ state=directory group=devs mode=2775 recurse=yes
    - name: Setting up custom privileges to logs directory
      action: file path=/var/www/html/internallogs state=directory owner=apache mode=2775 recurse=yes
    #- name: Setting up custom privileges to web directory
    #  shell: chgrp -R devs /var/www/html/ && find /var/www/html -type d -exec chmod -R 775 {}\;
    #- name: Modifing umask for apache user"
    #  action: copy src=etc/sysconfig/httpd dest=/etc/sysconfig/httpd owner=root group=root mode=0644
    - name: Making public apache log files
      action: file path=/var/log/httpd/ state=directory owner=root group=root mode=0755 
    - name: Applying changes to apache
      service: name=httpd state=reloaded


