---
# XYZ Python/Django project
- hosts: XYZ
  user: chef
  sudo: yes
  tasks:
    - name: Crear grupo para modificar archivos
      group: name=devs state=present    
    #- name: Adicionando usuario john.doe al grupo
    #  shell: useradd -G devs john.doe
    - name: Asignando ownership al directorio web
      action: file path=/var/www/html/ state=directory group=devs mode=2775 recurse=yes
    - name: Asignando ownership al directorio de trazas
      action: file path=/var/www/html/internallogs state=directory owner=apache mode=2775 recurse=yes
    #- name: Asignando permissions al directorio web
    #  shell: chgrp -R devs /var/www/html/ && find /var/www/html -type d -exec chmod -R 775 {}\;
    #- name: Modifing umask for apache user"
    #  action: copy src=etc/sysconfig/httpd dest=/etc/sysconfig/httpd owner=root group=root mode=0644
    - name: Making public apache log files
      action: file path=/var/log/httpd/ state=directory owner=root group=root mode=0755 
    - name: Applying changes to apache
      service: name=httpd state=reloaded


